@startuml
class "Reflection`1"<TF> {
    + GetFiledByName(name:string, obj:TF) : T
    + CompareByFieldName(name:string, first:TF, second:TF) : int
    + GetField(fieldName:string) : Func<TF, T>
    + GetComparator(fieldName:string) : Comparison<TF>
}
class "IReflection`1"<T> {
}
"IReflection`1" "<TF>" <|-- "Reflection`1"
@enduml
