@startuml
class Worker {
    + Worker(experience:uint, salary:double, birthday:DateOnly, name:string, job:string, sex:Sex, sickDays:int, vacation:int, bonus:double, taxes:List<Tax>)
    + Name : string <<get>> <<set>>
    + Job : string <<get>> <<set>>
    + Salary : double <<get>> <<set>>
    + Experience : uint <<get>> <<set>>
    + <<override>> GetSalary() : double
    + CompareTo(other:Worker?) : int
    + <<override>> ToString() : string
    + Clone() : object
    + AddTax(tax:Tax) : void
    + <<override>> DaysOnWork() : int
    + {static} Parse(str:string) : Worker
}
class "IComparable`1"<T> {
}
WorkerManagement <|-- Worker
"IComparable`1" "<Worker>" <|-- Worker
ICloneable <|-- Worker
Worker --> "Birthday" DateOnly
Worker --> "Sex" Sex
@enduml
